### ISSUE TITLE
lodash.clonedeep does not match - Installing using NPM doesn't work (Yarn does)

### ISSUE THREAD

**Issue by Vadorequest** [diegomura/react-log#14]
I'm trying to use this module but I get the following error at compile time:

> Failed to compile.
> 
> Error in ./~/react-log/dist/compiler/transformer.js
> Module not found: [CaseSensitivePathsPlugin] `/Users/vado/Documents/ws/ml-console/node_modules/react-log/node_modules/lodash.cloneDeep/index.js` does not match the corresponding path on disk `lodash.clonedeep`.
> 
>  @ ./~/react-log/dist/compiler/transformer.js 9:14-41

With the following package.json dependencies:

 ```
 "devDependencies": {
    "chai": "3.5.0",
    "chai-enzyme": "0.6.1",
    "enzyme": "2.7.1",
    "eslint": "3.12.2",
    "eslint-config-airbnb": "13.0.0",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-jsx-a11y": "2.2.3",
    "eslint-plugin-react": "6.8.0",
    "jest": "18.1.0",
    "react-addons-test-utils": "15.4.2",
    "react-dom": "15.4.2",
    "react-log": "2.3.0",
    "react-scripts": "0.8.5"
  },
  "dependencies": {
    "classnames": "2.2.5",
    "deep-equal": "1.0.1",
    "isomorphic-fetch": "2.2.1",
    "lodash.isempty": "4.4.0",
    "lodash.last": "3.0.0",
    "lodash.map": "4.6.0",
    "lodash.merge": "4.6.0",
    "lodash.snakecase": "4.1.1",
    "lodash.uniqby": "4.7.0",
    "query-string": "4.3.1",
    "react": "15.4.2",
    "react-addons-css-transition-group": "15.4.2",
    "react-addons-transition-group": "15.4.2",
    "react-broadcast": "0.1.2",
    "react-copy-to-clipboard": "4.2.3",
    "react-dom": "15.4.2",
    "react-imageloader": "2.1.0",
    "react-infinite-scroller": "1.0.4",
    "react-jss": "5.3.0",
    "react-redux": "4.4.6",
    "react-redux-toastr": "4.4.2",
    "react-router": "4.0.0-alpha.5",
    "react-select": "1.0.0-rc.2",
    "reactstrap": "3.9.5",
    "recompose": "0.21.2",
    "redux": "3.6.0",
    "redux-api": "0.9.16",
    "redux-form": "6.4.3",
    "redux-thunk": "2.1.0",
    "underscore.string": "3.3.4",
    "uuid": "3.0.1"
  },
```

Maybe lodash clonedeep has changed its name, there is char case difference. `cloneDeep` vs `clonedeep`

**Comment by Vadorequest** [comment]
I think it's because Yarn and NPM don't have the same name for clonedeep/cloneDeep and therefore the package doesn't have the same name. Tss.

I'm using npm, that's why it fails. Yarn is required.

**Comment by diegomura** [comment]
This method was being imported from `lodash.cloneDeep` instead of `loadah.clonedeep`.
Not sure why with yarn worked (maybe has some type of case checking?), but should be fixed now.

I'm releasing this fix now to npm. Please tell if this issue persist.
Thanks for reporting it!

**Comment by Vadorequest** [comment]
I believe npm is case sensitive but yarn isn't. Could be why, thanks for
the quick fix!

Le 3 févr. 2017 3:51 PM, "Diego Muracciole" <notifications@github.com> a
écrit :
